vertex:
  prefix: '#ffc84aVAC§7'

punish-effect:
  enabled: true
  particle_count: 80
  duration_ticks: 3
  particle: "FLAME"
  sound: "ENTITY_DRAGON_FIREBALL_EXPLODE"

alerts:
  # {prefix}
  # {player}
  # {check}
  # {violations}
  message: "{prefix} #ffebba{player} #ffc84afailed #ffebba{check} #ffc84a#{violations}"
  enable-alerts-on-join: true

messages:
  no-permission: "§cYou don't have permission to use this command"
  alerts:
    alerts-enabled: "§aAlerts enabled"
    alerts-disabled: "§cAlerts disabled"
  checks:
    header: "#ffc84aEnabled checks:"
    check: "#ffc84a- #ffebba{check}"
  config:
    config-reload: "§aReloading config..."
    config-reloaded: "§aConfig reloaded"
  commands: |
    #ffc84a- #ffebba/vertex reload &7- reload config
    #ffc84a- #ffebba/vertex checks &7- enabled checks
    #ffc84a- #ffebba/vertex help &7- help
    #ffc84a- #ffebba/vertex alerts &7- enable/disable alerts

checks:
  AimA:
    max-violations: 5
    remove-violations-after: 300 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    max-buffer: 1
    buffer-decrease: 0.1
    hit-cancel-ticks: 40
  AimB:
    max-violations: 10
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    max-buffer: 9
    buffer-decrease: 0.5
    hit-cancel-ticks: 10
  AimC:
    max-violations: 10
    remove-violations-after: 90 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    max-buffer: 2
    buffer-decrease: 0.5
    hit-cancel-ticks: 30
  AimD:
    max-violations: 2
    remove-violations-after: 300 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    hit-cancel-ticks: 80
  AimE:
    max-violations: 10
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    max-buffer: 9
    buffer-decrease: 1
    hit-cancel-ticks: 25
  AimF:
    max-violations: 3
    remove-violations-after: 600 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    max-buffer: 1
    buffer-decrease: 0.05
    hit-cancel-ticks: 200
  AimG:
    max-violations: 10
    remove-violations-after: 300 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    max-buffer: 3
    buffer-decrease: 0.5
    hit-cancel-ticks: 40
  AimH:
    max-violations: 15
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: false # false positive check
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    max-buffer: 2
    buffer-decrease: 0.25
    hit-cancel-ticks: 15
  AimI:
    max-violations: 15
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    max-buffer: 4
    buffer-decrease: 0.25
    hit-cancel-ticks: 15
  AimJ:
    max-violations: 10
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    max-buffer: 2
    buffer-decrease: 0.5
    hit-cancel-ticks: 20
  AimK:
    max-violations: 2
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    hit-cancel-ticks: 200
  AimL:
    max-violations: 15
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    max-buffer: 2
    buffer-decrease: 0.5
    hit-cancel-ticks: 30
  AimM:
    max-violations: 5
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    hit-cancel-ticks: 60
  AimN:
    max-violations: 5
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    hit-cancel-ticks: 25
  AimO:
    max-violations: 10
    remove-violations-after: 120 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    hit-cancel-ticks: 30
  AimP:
    max-violations: 10
    remove-violations-after: 120 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    hit-cancel-ticks: 40


  AuraA:
    max-violations: 10
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    max-buffer: 2
    buffer-decrease: 0.5
    hit-cancel-ticks: 100
  AuraB:
    max-violations: 10
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    max-buffer: 1
    buffer-decrease: 0.25
    hit-cancel-ticks: 40
  AuraC:
    max-violations: 15
    remove-violations-after: 120 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    max-buffer: 0
    buffer-decrease: 0
    hit-cancel-ticks: 0
  AuraD:
    max-violations: 5
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    hit-cancel-ticks: 0
  AuraE:
    max-violations: 15
    remove-violations-after: 120 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    max-buffer: 0
    buffer-decrease: 0
    hit-cancel-ticks: 0

  # data
  ActionData:
    combat-ticks: 60