# HEX available(#ffffff)
vertex:
  prefix: '§3VertexAnticheat§7'

punish-effect:
  enabled: true
  particle_count: 80
  duration_ticks: 3
  particle: "FLAME"
  sound: "ENTITY_DRAGON_FIREBALL_EXPLODE"

alerts:
  # {prefix}
  # {player}
  # {check}
  # {violations}
  message: "{prefix} §7{player} §3failed §7{check} §cVL: §7{violations}"
  enable-alerts-on-join: true

messages:
  no-permission: "§cYou don't have permission to use this command"
  alerts:
    alerts-enabled: "§aAlerts enabled"
    alerts-disabled: "§cAlerts disabled"
  checks:
    header: "§aEnabled checks:"
    check: "§3- #ffebba{check}"
  config:
    config-reload: "§aReloading config..."
    config-reloaded: "§aConfig reloaded"
  commands: |
    #ffc84a- #ffebba/vertex reload &7- reload config
    #ffc84a- #ffebba/vertex checks &7- enabled checks
    #ffc84a- #ffebba/vertex help &7- help
    #ffc84a- #ffebba/vertex alerts &7- enable/disable alerts

checks:
  AimA:
    max-violations: 5
    remove-violations-after: 300 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} §cUnfair Advantage'
    max-buffer: 1
    buffer-decrease: 0.1
  AimB:
    max-violations: 10
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} §cUnfair Advantage'
    max-buffer: 9
    buffer-decrease: 0.5
  AimC:
    max-violations: 10
    remove-violations-after: 90 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} §cUnfair Advantage'
    max-buffer: 2
    buffer-decrease: 0.5
  AimD:
    max-violations: 2
    remove-violations-after: 300 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} §cUnfair Advantage'
  AimE:
    max-violations: 10
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} §cUnfair Advantage'
    max-buffer: 9
    buffer-decrease: 1
  AimF:
    max-violations: 3
    remove-violations-after: 600 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} §cUnfair Advantage'
    max-buffer: 1
    buffer-decrease: 0.05
  AimG:
    max-violations: 10
    remove-violations-after: 300 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} §cUnfair Advantage'
    max-buffer: 3
    buffer-decrease: 0.5
  AimH:
    max-violations: 15
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: false # false positive check
    alert: true
    punish-command: 'kick {player} §cUnfair Advantage'
    max-buffer: 2
    buffer-decrease: 0.25
  AimI:
    max-violations: 15
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} §cUnfair Advantage'
    max-buffer: 4
    buffer-decrease: 0.25
  AimJ:
    max-violations: 10
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} §cUnfair Advantage'
    probability-threshold: 0.65

  AimK:
    max-violations: 2
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} §cUnfair Advantage'
  AimL:
    max-violations: 15
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} §cUnfair Advantage'
    max-buffer: 2
    probability-threshold: 0.6
  AimM:
    max-violations: 5
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} §cUnfair Advantage'
  AimN:
    max-violations: 5
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} §cUnfair Advantage'
  AimO:
    max-violations: 10
    remove-violations-after: 120 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} §cUnfair Advantage'

  AutoClickerA:
    max-violations: 10
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} §cUnfair Advantage'
    probability-threshold: 0.8

  AuraA:
    max-violations: 10
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} §cUnfair Advantage'
    max-buffer: 2
    buffer-decrease: 0.5
  AuraB:
    max-violations: 10
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} §cUnfair Advantage'
    max-buffer: 1
    buffer-decrease: 0.25
  AuraC:
    max-violations: 15
    remove-violations-after: 120 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} §cUnfair Advantage'
  AuraD:
    max-violations: 5
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} §cUnfair Advantage'
  AuraE:
    max-violations: 15
    remove-violations-after: 120 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} §cUnfair Advantage'

  # data
  ActionData:
    combat-ticks: 60